repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo02
repo_name: 2024.2-Grupo02

# TODO - MUDAR A LOGO E FAVICON QUANDO DECIDIR O APP

site_name: Moodle - Requisitos de Software
extra_css:
  - stylesheets/extra.css
theme:

    name: material
    palette:
      - scheme: slate #slate = dark, default = light
        primary: custom # cores - https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
        accent: custom
        toggle: 
            icon: material/brightness-4
            name: Modo escuro
        
      - scheme: default
        primary: custom
        accent: blue
        toggle:
            icon: material/brightness-7
            name: Modo claro
        
    locale: pt_br
    logo: ./img/logowhite.png # logo na barra de navegação do site
    favicon: ./img/logoslick.png # logo na aba do navegador
    
    
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
